server:
  port: 20061

spring:
  application:
    name: room-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      # 客户端类型（默认lettuce，可选jedis）
      client-type: lettuce
      # Lettuce客户端配置（原spring.redis.lettuce）
      lettuce:
        pool:
          # 连接池配置（原spring.redis.lettuce.pool）
          max-active: 8 # 最大活跃连接数
          max-idle: 8 # 最大空闲连接数
          min-idle: 2 # 最小空闲连接数
          max-wait: 10000ms # 连接最大等待时间
        shutdown-timeout: 100ms